INSERT INTO `achille_db`.`authority` (`authority`) VALUES ("ADMIN");
INSERT INTO `achille_db`.`authority` (`authority`) VALUES ("CONSULTANT");
INSERT INTO `achille_db`.`user` (`user_id`,`username`,`password`) VALUES (9998,"USER1","USER1");
INSERT INTO `achille_db`.`user` (`user_id`,`username`,`password`) VALUES (9999,"ADMIN","ADMIN");
INSERT INTO `achille_db`.`user_authority` (`user_user_id`, `authority_authority`) VALUES ('9999', 'ADMIN');
INSERT INTO `achille_db`.`user_authority` (`user_user_id`, `authority_authority`) VALUES ('9998', 'CONSULTANT');

INSERT INTO `achille_db`.`societe`(`value`) VALUES ("INTERVIA");
INSERT INTO `achille_db`.`societe`(`value`) VALUES ("B2M");
INSERT INTO `achille_db`.`societe`(`value`) VALUES ("INTERMISSION");
INSERT INTO `achille_db`.`societe`(`value`) VALUES ("SINOPIE");
INSERT INTO `achille_db`.`societe`(`value`) VALUES ("RONDOUDOU");

INSERT INTO `achille_db`.`type_contrat` (`value`) VALUES ("CDD");
INSERT INTO `achille_db`.`type_contrat` (`value`) VALUES ("CDI");


INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("2B CONSULTING");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("8POURCENT");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ABC SYSTEMES");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ACENSI");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ADMV");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ADNEOM");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ADYTON");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("AEZAN");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("AFD.TECH");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("AGILICIO");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("AGT INNOVATION");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("AKKA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ALADIUM");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ALEYSIA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ALLEGIS GROUP");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ALLIACOM");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ALMAVIA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ALTER SOLUTIONS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ALTEZIA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("AMEG");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("AMESSI");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("AMETIX");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ANTARES");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("APRILE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("APSIDE TOP");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("APTERYX FORMATIONS SARL");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ARCOSYS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ARKEMA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ARTHUR HUNT TRANSITION");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("AS DELIVERY");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ASAP CONSEIL");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ASENSIEL");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ASTAN INFORMATIQUE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ATTENTION TRAVAIL");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("AUDENSIEL");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("AUDENSIEL DIGITAL");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("AUDENSIEL TECHNOLOGIES SUD OUEST");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("AURA MAY");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("AUSY");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("AVA2I - LITTLE BIG CONNECTION");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("AVECVOO/MAYDAY");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("AVENIR CONSEIL FORMATION");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("AVENTURE PEUGEOT");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("BAI SA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("BEMORE MONACO");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("BHI");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("BIP DIFFUSION");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("BISCUIT HOLDING");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("BONNE PIOCHE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("BPCE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("BPCE IT");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("BRITTANY FERRIES");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("BROCELIA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("BUREAU VERITAS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("Business & Engineering Solutions");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("BVBA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("BVBA ATELIER HAIDER ACKBRMANN BVBA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("CARREFOUR");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("CARREFOUR (TJM 499,20€)");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("CE GEMALTO");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("CELAD");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("CHLOE SAS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("CMF CONSULTING");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("COMITEM");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("COMPUTER FUTURS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("CONSORT GROUP");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("CROSS KNOWLEDGE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("CS SYSTEMES d'INFORMATION");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("CTS NORD");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("CTY");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVEO");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON AQUITAINE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON ENERGIE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON EST");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON GRENOBLE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON INDUSTRIE LYON");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON INNOVATION & MOBILITE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON MIDI PYRENEES");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON NORD");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON OUEST");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON PACA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON PARIS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON RESEAUX ET MULTIMEDIA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON SI");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON SI NORD");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON SWITZERLAND");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON TECHNOLOGIES");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON TELECOM ET SI LYON");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON TELECOME ET SI LYON");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON TRANSPORTS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DAVIDSON TTA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DBV TECHNOLOGIES");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DCS EASYWARE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DEGETEL");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DELVILLE MANAGEMENT");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("DEVOTEAM");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("E3M MANAGEMENT");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ECONOCOM");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ELSYS Design");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("EMAGINE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ENTREPRENEURS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("EOLEN");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ESI");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ESI DIGITAL");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ETIENNE LACROIX");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("EULIDIA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("EUROSTAFF");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("EXPORT ENTREPRISE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("EXTEAM");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("Fédération Française du Sport Automobile");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("FFSA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("FHM INGENIERIE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("FIME");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("FINAXYS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("FNMF");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("FORMATEUR");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("FOTOFEVER");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("FREE TEAM IT");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("FULL ERP PERFORMANCE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("GALAXY SOFTWARE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("GEMALTO");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("GEOPHYSICS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("GFI");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("HARVEY NASH IT CONSLTING N.V");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("HAYS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("HEEM");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("HOXTON PARTNERS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("HR EXPERTISE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("HR TEAM");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("HUBSAN");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("HUXLEY");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("IBP");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("IDEMIA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("IDEX SERVICES");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("IFPASS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("INFODIS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("INFOGENE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("INFOTEL");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("INGEROP");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("INTERVIA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ISABEY GESTION");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("IT LINK");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("IT&M SOLUTIONS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("KEY CONSULTING");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("KEY4CAST");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("KEYWER");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("LAIINTERNATIONAL");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("LE GALEC");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("LEAP 29");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("LINA GORA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("LINEON");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("LOGTEAM");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("LOGWARE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("LUTECEO");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("LYNX RH");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("MAGELLAN");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("MARGIELA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("MATIS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("MBA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("MCG");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("MEGA SERVICES");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("MICHELIN");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("MISYS France");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("MOHAMED SOUIAI");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("MONTREAL");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("MOOSE MILANO");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("MPA SERVICE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("MPEARL");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("MPI PARTNERS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("MYRIAD");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("NEXTEDIA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("NEXTER MUNITIONS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("NIGEL FRANCK INTERNATIONAL");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("NIGEL FRANCK INTERNATIONAL LIMITED");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("NIJI");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("OBERTHUR");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("OCSIGROUP");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("OLIGOS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ONEPOINT");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("OPENMINDED");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("OPTEAMIS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("OWENTIS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("PACO RABANNE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("PANDA SERVICES");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("PARAGRAPH");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("PAYLIB SERVICES");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("PI SERVICES");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("PICKMEUP");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("PREMIUM PEERS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("PRIME ENGINEERING");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("PROCADRES");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("PROCADRES SUISSE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("PROGRESSIVE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("PROXIAD IDF SAS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("QUINTEN");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("RATP");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("RCH CONSULTING");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("RED SAP SOLUTIONS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ROBONOTIC");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("ROIK");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("RSB FRANCE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("SAMSUNG");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("SAPSTARS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("SCORE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("SEMOFI");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("SGS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("SHIFT CONSULTING");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("SIKHOM");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("SISMOCEAN");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("SNCF");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("SOAT");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("SOFTCOMPANY");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("SOM");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("SOM CALCUL");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("SPIE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("STA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("STREIT");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("STS MANAGEMENT");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("STX France");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("SUNLOG TECHNOLOGIE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("SYSTEMIS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("TALAN");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("TALAN CORPORATE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("TEK KER");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("TELITEM PARIS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("TEXELIS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("TLTI");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("TLTI INFORMATIQUE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("TREVES");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("TRSB");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("UBS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("UCC EXPERTS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("UNIWARE GLOBAL SERVICES");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("V&A FASHION");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("VALLOUREC");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("VALTUS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("VENEDIM");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("VIVREA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("XPM TRANSITION PARTNERS");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("YELE");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("YOMEVA");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("YOSEMITE INVEST");
INSERT INTO `achille_db`.`partenaire` (`value`) VALUES ("YVES SAINT LAURENT BEAUTE");
