INSERT INTO `achille_db`.`authority` (`authority`) VALUES ("ADMIN");
INSERT INTO `achille_db`.`authority` (`authority`) VALUES ("CONSULTANT");
INSERT INTO `achille_db`.`user` (`user_id`,`username`,`password`) VALUES (1,"TEST","TEST");
INSERT INTO `achille_db`.`user` (`user_id`,`username`,`password`) VALUES (2,"USER1","USER1");
INSERT INTO `achille_db`.`user` (`user_id`,`username`,`password`) VALUES (3,"ADMIN","ADMIN");
INSERT INTO `achille_db`.`user_authority` (`user_user_id`, `authority_authority`) VALUES ('1', 'ADMIN');
INSERT INTO `achille_db`.`user_authority` (`user_user_id`, `authority_authority`) VALUES ('1', 'CONSULTANT');
INSERT INTO `achille_db`.`user_authority` (`user_user_id`, `authority_authority`) VALUES ('2', 'CONSULTANT');
INSERT INTO `achille_db`.`user_authority` (`user_user_id`, `authority_authority`) VALUES ('3', 'ADMIN');

INSERT INTO `achille_db`.`societe`(`societe`) VALUES ("INTERVIA");
INSERT INTO `achille_db`.`societe`(`societe`) VALUES ("B2M");
INSERT INTO `achille_db`.`societe`(`societe`) VALUES ("INTERMISSION");
INSERT INTO `achille_db`.`societe`(`societe`) VALUES ("SINOPIE");
INSERT INTO `achille_db`.`societe`(`societe`) VALUES ("RONDOUDOU");

INSERT INTO `achille_db`.`type_contrat` (`type_contrat`) VALUES ("CDD");
INSERT INTO `achille_db`.`type_contrat` (`type_contrat`) VALUES ("CDD USAGE ETRANGER");
INSERT INTO `achille_db`.`type_contrat` (`type_contrat`) VALUES ("CDD USAGE");
INSERT INTO `achille_db`.`type_contrat` (`type_contrat`) VALUES ("CDD RETRAITE ?");
INSERT INTO `achille_db`.`type_contrat` (`type_contrat`) VALUES ("CDI");
INSERT INTO `achille_db`.`type_contrat` (`type_contrat`) VALUES ("CDI INTERNE");
INSERT INTO `achille_db`.`type_contrat` (`type_contrat`) VALUES ("CDI / CDIC");
INSERT INTO `achille_db`.`type_contrat` (`type_contrat`) VALUES ("CDI RETRAITE");
INSERT INTO `achille_db`.`type_contrat` (`type_contrat`) VALUES ("CDI RETRAITE ?");

INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("2B CONSULTING");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("8POURCENT");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ABC SYSTEMES");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ACENSI");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ADMV");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ADNEOM");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ADYTON");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("AEZAN");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("AFD.TECH");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("AGILICIO");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("AGT INNOVATION");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("AKKA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ALADIUM");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ALEYSIA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ALLEGIS GROUP");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ALLIACOM");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ALMAVIA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ALTER SOLUTIONS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ALTEZIA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("AMEG");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("AMESSI");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("AMETIX");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ANTARES");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("APRILE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("APSIDE TOP");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("APTERYX FORMATIONS SARL");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ARCOSYS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ARKEMA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ARTHUR HUNT TRANSITION");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("AS DELIVERY");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ASAP CONSEIL");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ASENSIEL");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ASTAN INFORMATIQUE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ATTENTION TRAVAIL");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("AUDENSIEL");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("AUDENSIEL DIGITAL");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("AUDENSIEL TECHNOLOGIES SUD OUEST");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("AURA MAY");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("AUSY");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("AVA2I - LITTLE BIG CONNECTION");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("AVECVOO/MAYDAY");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("AVENIR CONSEIL FORMATION");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("AVENTURE PEUGEOT");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("BAI SA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("BEMORE MONACO");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("BHI");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("BIP DIFFUSION");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("BISCUIT HOLDING");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("BONNE PIOCHE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("BPCE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("BPCE IT");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("BRITTANY FERRIES");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("BROCELIA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("BUREAU VERITAS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("Business & Engineering Solutions");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("BVBA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("BVBA ATELIER HAIDER ACKBRMANN BVBA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("CARREFOUR");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("CARREFOUR (TJM 499,20€)");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("CE GEMALTO");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("CELAD");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("CHLOE SAS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("CMF CONSULTING");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("COMITEM");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("COMPUTER FUTURS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("CONSORT GROUP");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("CROSS KNOWLEDGE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("CS SYSTEMES d'INFORMATION");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("CTS NORD");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("CTY");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVEO");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON AQUITAINE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON ENERGIE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON EST");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON GRENOBLE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON INDUSTRIE LYON");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON INNOVATION & MOBILITE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON MIDI PYRENEES");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON NORD");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON OUEST");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON PACA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON PARIS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON RESEAUX ET MULTIMEDIA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON SI");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON SI NORD");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON SWITZERLAND");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON TECHNOLOGIES");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON TELECOM ET SI LYON");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON TELECOME ET SI LYON");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON TRANSPORTS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DAVIDSON TTA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DBV TECHNOLOGIES");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DCS EASYWARE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DEGETEL");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DELVILLE MANAGEMENT");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("DEVOTEAM");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("E3M MANAGEMENT");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ECONOCOM");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ELSYS Design");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("EMAGINE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ENTREPRENEURS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("EOLEN");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ESI");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ESI DIGITAL");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ETIENNE LACROIX");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("EULIDIA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("EUROSTAFF");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("EXPORT ENTREPRISE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("EXTEAM");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("Fédération Française du Sport Automobile");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("FFSA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("FHM INGENIERIE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("FIME");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("FINAXYS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("FNMF");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("FORMATEUR");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("FOTOFEVER");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("FREE TEAM IT");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("FULL ERP PERFORMANCE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("GALAXY SOFTWARE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("GEMALTO");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("GEOPHYSICS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("GFI");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("HARVEY NASH IT CONSLTING N.V");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("HAYS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("HEEM");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("HOXTON PARTNERS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("HR EXPERTISE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("HR TEAM");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("HUBSAN");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("HUXLEY");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("IBP");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("IDEMIA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("IDEX SERVICES");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("IFPASS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("INFODIS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("INFOGENE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("INFOTEL");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("INGEROP");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("INTERVIA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ISABEY GESTION");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("IT LINK");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("IT&M SOLUTIONS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("KEY CONSULTING");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("KEY4CAST");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("KEYWER");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("LAIINTERNATIONAL");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("LE GALEC");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("LEAP 29");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("LINA GORA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("LINEON");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("LOGTEAM");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("LOGWARE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("LUTECEO");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("LYNX RH");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("MAGELLAN");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("MARGIELA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("MATIS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("MBA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("MCG");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("MEGA SERVICES");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("MICHELIN");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("MISYS France");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("MOHAMED SOUIAI");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("MONTREAL");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("MOOSE MILANO");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("MPA SERVICE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("MPEARL");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("MPI PARTNERS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("MYRIAD");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("NEXTEDIA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("NEXTER MUNITIONS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("NIGEL FRANCK INTERNATIONAL");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("NIGEL FRANCK INTERNATIONAL LIMITED");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("NIJI");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("OBERTHUR");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("OCSIGROUP");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("OLIGOS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ONEPOINT");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("OPENMINDED");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("OPTEAMIS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("OWENTIS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("PACO RABANNE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("PANDA SERVICES");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("PARAGRAPH");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("PAYLIB SERVICES");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("PI SERVICES");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("PICKMEUP");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("PREMIUM PEERS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("PRIME ENGINEERING");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("PROCADRES");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("PROCADRES SUISSE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("PROGRESSIVE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("PROXIAD IDF SAS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("QUINTEN");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("RATP");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("RCH CONSULTING");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("RED SAP SOLUTIONS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ROBONOTIC");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("ROIK");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("RSB FRANCE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("SAMSUNG");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("SAPSTARS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("SCORE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("SEMOFI");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("SGS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("SHIFT CONSULTING");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("SIKHOM");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("SISMOCEAN");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("SNCF");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("SOAT");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("SOFTCOMPANY");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("SOM");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("SOM CALCUL");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("SPIE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("STA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("STREIT");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("STS MANAGEMENT");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("STX France");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("SUNLOG TECHNOLOGIE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("SYSTEMIS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("TALAN");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("TALAN CORPORATE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("TEK KER");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("TELITEM PARIS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("TEXELIS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("TLTI");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("TLTI INFORMATIQUE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("TREVES");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("TRSB");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("UBS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("UCC EXPERTS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("UNIWARE GLOBAL SERVICES");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("V&A FASHION");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("VALLOUREC");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("VALTUS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("VENEDIM");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("VIVREA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("XPM TRANSITION PARTNERS");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("YELE");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("YOMEVA");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("YOSEMITE INVEST");
INSERT INTO `achille_db`.`partenaire` (`partenaire`) VALUES ("YVES SAINT LAURENT BEAUTE");
